[[project]]
title = "Payment API"
base-url = "http://localhost:8000"

[reports.junit]
path = "./test-reports/schemathesis-results.xml"

[auth.dynamic.openapi.HTTPBearer]
path = "/auth/login"
payload = { email = "user@example.com", password = "string" }
extract_selector = "/access_token"

