[[project]]
title = "RAG Assistant API"
base-url = "http://localhost:8000"

[[operations]] 
include-name = "POST /files"
enabled = false

[[operations]]
include-name = "GET /files/{file_id}/"
parameters = { "path.file_id" = "8642b4cc-ffad-49ab-bbf0-6cc9ac7b65cd"}
